/**
 * Validation schemas for the emergency-transfer flow.
 *
 * Three schemas are exported:
 *  1. EmergencyTransferConfigSchema  – validates a raw config before it is
 *     frozen into an EmergencyTransferConfig model.
 *  2. ConfirmationPayloadSchema      – validates the bound payload that the
 *     sign step receives; guards against stale / tampered state.
 *  3. RiskAcknowledgementSchema      – validates that the user explicitly
 *     accepted the risk notice with the exact expected text.
 *
 * Security note: every field that influences what gets signed is included in
 * ConfirmationPayloadSchema.  The sign handler must re-validate this schema
 * server-side so a manipulated client payload cannot bypass the gate.
 */

import { z } from 'zod'
import type { NetworkId } from '@/models/emergency-transfer-config'

// ---------------------------------------------------------------------------
// Primitive helpers
// ---------------------------------------------------------------------------

/** Non-empty string trimmed of surrounding whitespace. */
const nonEmptyString = z.string().trim().min(1, 'Required')

/**
 * Ethereum-style hex address or 32-58 character base58/bech32 address.
 * Allows both EVM (0x…) and non-EVM (Solana, Stellar) formats.
 */
const recipientAddress = nonEmptyString
  .min(26, 'Invalid recipient address format')
  .max(128, 'Recipient address is too long')
  .refine(
    (v) =>
      /^0x[0-9a-fA-F]{40}$/.test(v) || // EVM checksummed / non-checksummed
      /^[1-9A-HJ-NP-Za-km-z]{32,58}$/.test(v) || // base58 (Solana, Bitcoin)
      /^[A-Z0-9]{56}$/.test(v), // Stellar G… address (stripped)
    'Invalid recipient address format',
  )

/**
 * Unsigned integer string — the raw amount in the token's smallest unit.
 * We refuse floats to prevent precision loss.
 */
const rawAmountString = nonEmptyString
  .regex(/^\d+$/, 'Amount must be a non-negative integer string (smallest unit)')
  .refine(
    (v) => {
      try {
        return BigInt(v) > BigInt(0)
      } catch {
        return false
      }
    },
    'Amount must be greater than zero',
  )



/** Token symbol — letters, digits, hyphens, max 20 chars. */
const tokenSymbol = nonEmptyString
  .max(20, 'Asset symbol too long')
  .regex(/^[A-Za-z0-9\-]+$/, 'Asset symbol contains invalid characters')

/** Contract address: either 0x… or empty string for native assets. */
const contractAddress = z
  .string()
  .refine(
    (v) => v === '' || /^0x[0-9a-fA-F]{40}$/.test(v),
    'Contract address must be a valid EVM address or empty string for native assets',
  )

const SUPPORTED_NETWORKS: NetworkId[] = [
  'ethereum',
  'polygon',
  'arbitrum',
  'optimism',
  'base',
  'solana',
  'stellar',
]

const networkId = z.enum(SUPPORTED_NETWORKS as [NetworkId, ...NetworkId[]], {
  errorMap: () => ({
    message: `Network must be one of: ${SUPPORTED_NETWORKS.join(', ')}`,
  }),
})

// ---------------------------------------------------------------------------
// Sub-schemas
// ---------------------------------------------------------------------------

export const AssetDescriptorSchema = z.object({
  symbol: tokenSymbol,
  contractAddress,
  decimals: z
    .number()
    .int('Decimals must be an integer')
    .min(0, 'Decimals cannot be negative')
    .max(36, 'Decimals value is unreasonably large'),
})

// ---------------------------------------------------------------------------
// 1. EmergencyTransferConfigSchema
// ---------------------------------------------------------------------------

/**
 * Validates the raw parameters supplied by a caller before they are passed
 * to `createEmergencyTransferConfig`.  The `configId` and `createdAt` fields
 * are omitted because they are generated by the factory.
 */
export const EmergencyTransferConfigSchema = z
  .object({
    expiresAt: z
      .number()
      .int()
      .refine((v) => v > Date.now(), {
        message: 'expiresAt must be in the future',
      }),
    recipient: recipientAddress,
    amountRaw: rawAmountString,
    amountDisplay: nonEmptyString.max(64, 'amountDisplay is too long'),
    asset: AssetDescriptorSchema,
    networkId,
    authorizedBy: z
      .string()
      .min(1, 'authorizedBy must identify the authorising principal')
      .nullable(),
    memo: z.string().max(256, 'Memo exceeds 256 characters').optional(),
    quoteId: z.string().max(128, 'quoteId is too long').optional(),
    quoteHash: z.string().max(128, 'quoteHash is too long').optional(),
    requestKey: z.string().max(128, 'requestKey is too long').optional(),
    nonce: z.string().max(128, 'nonce is too long').optional(),
  })
  .strict()

export type EmergencyTransferConfigInput = z.infer<typeof EmergencyTransferConfigSchema>

// ---------------------------------------------------------------------------
// 2. ConfirmationPayloadSchema
// ---------------------------------------------------------------------------

/**
 * The payload that is constructed during the review step and passed
 * unchanged to the sign step.  All identity fields are re-validated so
 * any drift between review and sign is detected immediately.
 *
 * The `bindingKey` ties this payload to a specific `(configId, reviewedAt)`
 * tuple and must survive an equality check in the sign handler.
 */
export const ConfirmationPayloadSchema = z
  .object({
    configId: nonEmptyString,
    bindingKey: nonEmptyString.regex(
      /^bk_[0-9a-f]{8}$/,
      'Invalid binding key format',
    ),
    /** UTC epoch ms when the user completed review and bound the payload. */
    reviewedAt: z.number().int().positive(),
    /** UTC epoch ms copied from the config — confirmed still in the future. */
    expiresAt: z
      .number()
      .int()
      .refine((v) => v > Date.now(), {
        message: 'Confirmation payload has expired — start a new review',
      }),
    recipient: recipientAddress,
    amountRaw: rawAmountString,
    amountDisplay: nonEmptyString.max(64),
    asset: AssetDescriptorSchema,
    networkId,
    authorizedBy: z.string().min(1).nullable(),
    memo: z.string().max(256).optional(),
    quoteId: z.string().max(128).optional(),
    quoteHash: z.string().max(128).optional(),
    requestKey: z.string().max(128).optional(),
    nonce: z.string().max(128).optional(),
    /** Must be true — the user must have ticked the risk acknowledgement. */
    riskAcknowledged: z.literal(true, {
      errorMap: () => ({ message: 'Risk acknowledgement is required' }),
    }),
    /** Exact text the user confirmed in the acknowledgement checkbox. */
    acknowledgedText: nonEmptyString,
  })
  .strict()

export type ConfirmationPayload = z.infer<typeof ConfirmationPayloadSchema>

// ---------------------------------------------------------------------------
// 3. RiskAcknowledgementSchema
// ---------------------------------------------------------------------------

/**
 * The canonical risk-acknowledgement text.  This exact string is rendered
 * in the UI checkbox label and verified against the payload field so the
 * frontend cannot silently show softer wording.
 */
export const RISK_ACKNOWLEDGEMENT_TEXT =
  'I understand this is an emergency transfer. I confirm the recipient address, amount, asset, and network shown above are correct and that this action cannot be undone once submitted.'

export const RiskAcknowledgementSchema = z.object({
  acknowledged: z.literal(true, {
    errorMap: () => ({ message: 'You must acknowledge the risk to proceed' }),
  }),
  acknowledgedText: z.literal(RISK_ACKNOWLEDGEMENT_TEXT, {
    errorMap: () => ({
      message:
        'Acknowledged text does not match the required risk statement',
    }),
  }),
})

export type RiskAcknowledgement = z.infer<typeof RiskAcknowledgementSchema>

// ---------------------------------------------------------------------------
// Cross-field guard: config ↔ payload binding check
// ---------------------------------------------------------------------------

/**
 * Verifies that a `ConfirmationPayload` was derived from the given
 * `configId`, `recipient`, `amountRaw`, `asset`, `networkId`, and
 * `expiresAt`.  Returns `true` when the payload is still valid.
 *
 * This is the server-side equivalent of `configsMatch` and is intentionally
 * kept as a pure function so it can be called in both middleware and tests.
 */
export function assertPayloadMatchesConfig(
  payload: ConfirmationPayload,
  config: {
    configId: string
    recipient: string
    amountRaw: string
    asset: { symbol: string; contractAddress: string; decimals: number }
    networkId: string
    expiresAt: number
    memo?: string
    quoteId?: string
    quoteHash?: string
    requestKey?: string
    nonce?: string
  },
): void {
  const mismatches: string[] = []

  if (payload.configId !== config.configId)
    mismatches.push('configId')
  if (payload.recipient !== config.recipient)
    mismatches.push('recipient')
  if (payload.amountRaw !== config.amountRaw)
    mismatches.push('amountRaw')
  if (payload.asset.symbol !== config.asset.symbol)
    mismatches.push('asset.symbol')
  if (payload.asset.contractAddress !== config.asset.contractAddress)
    mismatches.push('asset.contractAddress')
  if (payload.asset.decimals !== config.asset.decimals)
    mismatches.push('asset.decimals')
  if (payload.networkId !== config.networkId)
    mismatches.push('networkId')
  if (payload.expiresAt !== config.expiresAt)
    mismatches.push('expiresAt')
  if (payload.memo !== config.memo)
    mismatches.push('memo')
  if (payload.quoteId !== config.quoteId)
    mismatches.push('quoteId')
  if (payload.quoteHash !== config.quoteHash)
    mismatches.push('quoteHash')
  if (payload.requestKey !== config.requestKey)
    mismatches.push('requestKey')
  if (payload.nonce !== config.nonce)
    mismatches.push('nonce')

  if (mismatches.length > 0) {
    throw new Error(
      `Confirmation payload does not match the reviewed config. ` +
        `Mismatched fields: ${mismatches.join(', ')}. ` +
        `A new review is required.`,
    )
  }
}

