/**
 * EmergencyTransferConfig
 *
 * Immutable description of an authorised emergency-transfer operation.
 * All fields that influence what gets signed are captured here so that
 * the confirmation step can verify nothing has drifted since review.
 *
 * Security invariant: once a config is handed to the review panel it
 * must never be mutated.  Any caller change (recipient, amount, network,
 * asset) must produce a new config with a new `configId` and `createdAt`,
 * which automatically invalidates any in-progress review.
 */

/** Supported network identifiers – extend as needed. */
export type NetworkId =
  | 'ethereum'
  | 'polygon'
  | 'arbitrum'
  | 'optimism'
  | 'base'
  | 'solana'
  | 'stellar'

/** An asset on a specific network. */
export interface AssetDescriptor {
  /** Canonical symbol, e.g. "USDC", "ETH". */
  symbol: string
  /** Token contract address (empty string for native assets). */
  contractAddress: string
  /** Decimal precision of the token. */
  decimals: number
}

/**
 * Fully-specified parameters for one emergency transfer.
 *
 * `Object.freeze` is applied by the factory so callers cannot mutate it
 * at runtime.  TypeScript `readonly` enforces this at compile time.
 */
export interface EmergencyTransferConfig {
  /** Opaque unique identifier generated by `createEmergencyTransferConfig`. */
  readonly configId: string
  /** UTC epoch ms when this config was created. */
  readonly createdAt: number
  /** UTC epoch ms after which this config is considered expired. */
  readonly expiresAt: number
  /** Checksummed recipient address or public key. */
  readonly recipient: string
  /**
   * Transfer amount expressed as a whole-number string in the smallest
   * unit of the asset (e.g. wei for ETH, lamports for SOL, stroops for XLM).
   * Using a string avoids floating-point precision loss.
   */
  readonly amountRaw: string
  /** Human-readable amount in canonical (display) units, pre-formatted. */
  readonly amountDisplay: string
  /** Asset being transferred. */
  readonly asset: AssetDescriptor
  /** Target network. */
  readonly networkId: NetworkId
  /**
   * Authorisation principal that approved this transfer at the policy level.
   * The UI disables the action when this is `null`.
   */
  readonly authorizedBy: string | null
  /** Optional free-text memo that will be embedded in the transaction. */
  readonly memo?: string
  /** Authorized quote identifier tying transfer terms to policy approval. */
  readonly quoteId?: string
  /** Hash digest of quote terms (rate, fees, output amount). */
  readonly quoteHash?: string
  /** Client-side or backend-issued durable request key for idempotency. */
  readonly requestKey?: string
  /** One-time nonce binding for replay protection. */
  readonly nonce?: string
}

/** Factory that creates a frozen, immutable config with a derived configId. */
export function createEmergencyTransferConfig(
  params: Omit<EmergencyTransferConfig, 'configId' | 'createdAt'> & {
    configId?: string
  },
): EmergencyTransferConfig {
  const now = Date.now()
  const raw = `${params.quoteId ?? ''}:${params.requestKey ?? ''}:${params.nonce ?? ''}:${params.recipient}:${params.amountRaw}:${params.asset.symbol}:${params.networkId}:${now}`
  const derivedConfigId = btoa(raw).replace(/[^a-zA-Z0-9]/g, '').slice(0, 32)
  const configId = params.configId ?? derivedConfigId

  const config: EmergencyTransferConfig = Object.freeze({
    ...params,
    configId,
    createdAt: now,
  })

  return config
}

/**
 * Returns `true` when the config has passed its `expiresAt` timestamp.
 * The confirmation step must reject expired configs.
 */
export function isConfigExpired(config: EmergencyTransferConfig, now = Date.now()): boolean {
  return now >= config.expiresAt
}

/**
 * Returns `true` when all identity fields of two configs match exactly.
 * Used by the confirmation step to detect stale-state drift between
 * review and sign.
 */
export function configsMatch(a: EmergencyTransferConfig, b: EmergencyTransferConfig): boolean {
  return (
    a.configId === b.configId &&
    a.recipient === b.recipient &&
    a.amountRaw === b.amountRaw &&
    a.asset.symbol === b.asset.symbol &&
    a.asset.contractAddress === b.asset.contractAddress &&
    a.asset.decimals === b.asset.decimals &&
    a.networkId === b.networkId &&
    a.expiresAt === b.expiresAt &&
    a.memo === b.memo &&
    a.quoteId === b.quoteId &&
    a.quoteHash === b.quoteHash &&
    a.requestKey === b.requestKey &&
    a.nonce === b.nonce
  )
}

